<a href="https://colab.research.google.com/github/InigoMathieuCelestino/58013LinearAlgebra/blob/main/Determinant_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Determinant of Matrix

In [3]:
# Determinant of Matrix
# 3x3 Matrix

import numpy as np

A = np.array([[1, 2, -1],[4, 6, -2],[-1, 3, 3]])
print(A)
round(np.linalg.det(A))

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]


-14