<a href="https://colab.research.google.com/github/InigoMathieuCelestino/58013LinearAlgebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PROBLEM 1

In [35]:
# Matrix Multiplied By A Matrix

# Matrix 2X3
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)

# Matrix 3X2
B = np.array([[1, 2],[3, 4],[5, 6]])
print(B)

R = [[sum(a * b for a, b in zip(A_row, B_col))
                        for B_col in zip(*B)]
                                for A_row in A]
print(R)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[22, 28], [49, 64]]


In [34]:
# Vector Addition
import numpy as np
D1 = np.array([[1, 2],[3, 4]])
print(D1)
D2 = np.array([[1, 2],[3, 4]])
print(D2)

R = D1 + D2
print(R)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


In [33]:
# Matrix Multiplied By A Single Integer

import numpy as np
C = np.array ([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
print(C)

R = 2 * C
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


PROBLEM 2

In [32]:
# Cross Product Of Matrices

import numpy as np
A = np.array ([2,7,4])
B = np.array ([[3],[9],[8]])

R = A * B
print(R)

[[ 6 21 12]
 [18 63 36]
 [16 56 32]]
