<a href="https://colab.research.google.com/github/InigoMathieuCelestino/58013LinearAlgebra/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PRELIM EXAM

In [3]:
# MULTIPLICATION TABLE OF 1-10

import numpy as np

def mult_table(N):
    R = np.arange(1, N+1)
    return R * R[:, None]

print(mult_table(10))


# DOUBLE THE VALUES OF EACH ELEMENT

print(mult_table(10)*2)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
[[  2   4   6   8  10  12  14  16  18  20]
 [  4   8  12  16  20  24  28  32  36  40]
 [  6  12  18  24  30  36  42  48  54  60]
 [  8  16  24  32  40  48  56  64  72  80]
 [ 10  20  30  40  50  60  70  80  90 100]
 [ 12  24  36  48  60  72  84  96 108 120]
 [ 14  28  42  56  70  84  98 112 126 140]
 [ 16  32  48  64  80  96 112 128 144 160]
 [ 18  36  54  72  90 108 126 144 162 180]
 [ 20  40  60  80 100 120 140 160 180 200]]


In [16]:
# PROPERTY OF MATRIX
# IDENTITY MATRIX
# SQUARE MATRIX DIAGONAL 1's

A = np.array([1, 1, 1, 1])
D = np.diag(A)

print(D)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [29]:
# MATRIX'S SHAPE, SIZE AND DIMENSION

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(matrix)

# SHAPE

S = np.shape(matrix)
print(S)

# SIZE

SZ = np.size(matrix)
print(SZ)

# DIMENSION

D = np.ndim(matrix)
print(D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
12
2


In [30]:
# ADDITION OF TWO NUMPY ARRAYS
import numpy as np

arrayOne = np.array([[5, 6, 9], [21,18, 27]])
arrayTwo = np.array([[15,33, 24], [4,7, 1]])

ADD = arrayOne + arrayTwo
print (ADD)

# SQUARE EACH ELEMENT

SQ = ADD ** 2
print(SQ)

[[20 39 33]
 [25 25 28]]
[[ 400 1521 1089]
 [ 625  625  784]]
