<a href="https://colab.research.google.com/github/InigoMathieuCelestino/58013LinearAlgebra/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vector Operations


In [15]:
# Vector Addition

import numpy as np
A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])

R = A+B+C
print(R)

R2 = np.add(A,B,C)
print(R2)

R3 = np.sum(B)
print(R3)

# Vector Subtraction

R4 = np.subtract(A,B)
print(R4)

R5 = A-B
print(R5)

# Vector Multiplication

R6 = np.multiply(A,B)

R7 = A*B
print(R7)

# Vector Division

R8 = np.divide(A,B)

R9 = A/B
print(R9)

C = np.array([3.9,1.8,7.7])
D = np.array([1,1,1])

R10 = C//D
print(R10)

R11 = np.array(A/B,dtype=int)
print(R11)

[ 4  3 -1]
[ 4  3 -2]
2
[-2  1  2]
[-2  1  2]
[3 2 0]
[ 0.33333333  2.         -0.        ]
[3. 1. 7.]
[0 2 0]
