<a href="https://colab.research.google.com/github/InigoMathieuCelestino/58013LinearAlgebra/blob/main/Special_Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SPECIAL PRELIM EXAM

In [7]:
# Multiplication Table of 10

import numpy as np

def x_table(N):
    R = np.arange(1, N+1)
    return R * R[:, None]

print(x_table(10))

# Triple the values of each element

print(x_table(10)*3)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
[[  3   6   9  12  15  18  21  24  27  30]
 [  6  12  18  24  30  36  42  48  54  60]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 12  24  36  48  60  72  84  96 108 120]
 [ 15  30  45  60  75  90 105 120 135 150]
 [ 18  36  54  72  90 108 126 144 162 180]
 [ 21  42  63  84 105 126 147 168 189 210]
 [ 24  48  72  96 120 144 168 192 216 240]
 [ 27  54  81 108 135 162 189 216 243 270]
 [ 30  60  90 120 150 180 210 240 270 300]]


In [19]:
# Square Matrix
# Diagonal of 5's

import numpy as np

F = np.array([5, 5, 5, 5])
R = np.diag(F)

print(R)

[[5 0 0 0]
 [0 5 0 0]
 [0 0 5 0]
 [0 0 0 5]]


In [18]:
# Matrix's Size, Shape and Dimension

import numpy as np

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(matrix)

# Shape

S = np.shape(matrix)
print(S)

# Size

SZ = np.size(matrix)
print(SZ)

# Dimension

D = np.ndim(matrix)
print(D)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
12
2


In [25]:
# Subtraction of two numpy arrays

import numpy as np

arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

SUB = np.subtract(arrayOne, arrayTwo)
print(SUB)

# Square each element

SQ = np.square(SUB)
print(SQ)

[[-10 -27 -15]
 [ 17  11  26]]
[[100 729 225]
 [289 121 676]]
