<a href="https://colab.research.google.com/github/InigoMathieuCelestino/58013LinearAlgebra/blob/main/Vector%2C_Spaces_and_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])

print('Vector A is ', A)
print('Vector B is ', B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


In [25]:
### Checking shapes
### Shapes tells us how many rows and columns are there
import numpy as np
ball1 = np.array([[1],[2],[3]])
ball2 = np.array([0,1,-1])
print(ball1)
print(ball2)
ball = np.shape(ball1 + ball2)
print(ball)

[[1]
 [2]
 [3]]
[ 0  1 -1]
(3, 3)


In [31]:
### Checking shapes
### Shapes tells us how many rows and columns are there
import numpy as np
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
print(ball1)
print(ball2)
ball = np.shape(ball1)
balls = np.shape(ball2)
x = ball + balls
print(x)

[1 2 3]
[ 0  1 -1]
(3, 3)


In [46]:
# Vector Addition
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])

R = A + B
print(R)

[ 6 -2]


In [47]:
# Vector Subtraction
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])

R = A - B
print(R)

[2 8]


In [48]:
# Vector Multiplication
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])

R = A * B
print(R)

[  8 -15]


In [49]:
# Scalar Product
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])
S = np.array ([2])
R = S * A
print(R)

[8 6]


In [51]:
# Dot Product
import numpy as np
A = np.array ([4,3])
B = np.array ([[2],[-5]])
R = A * B
print(R)

[[  8   6]
 [-20 -15]]
