<a href="https://colab.research.google.com/github/InigoMathieuCelestino/58013LinearAlgebra/blob/main/Vector%2C_Spaces_and_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])

print('Vector A is ', A)
print('Vector B is ', B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


In [25]:
### Checking shapes
### Shapes tells us how many rows and columns are there
import numpy as np
ball1 = np.array([[1],[2],[3]])
ball2 = np.array([0,1,-1])
print(ball1)
print(ball2)
ball = np.shape(ball1 + ball2)
print(ball)

[[1]
 [2]
 [3]]
[ 0  1 -1]
(3, 3)


In [31]:
### Checking shapes
### Shapes tells us how many rows and columns are there
import numpy as np
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
print(ball1)
print(ball2)
ball = np.shape(ball1)
balls = np.shape(ball2)
x = ball + balls
print(x)

[1 2 3]
[ 0  1 -1]
(3, 3)


In [46]:
# Vector Addition
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])

R = A + B
print(R)

[ 6 -2]


In [47]:
# Vector Subtraction
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])

R = A - B
print(R)

[2 8]


In [48]:
# Vector Multiplication
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])

R = A * B
print(R)

[  8 -15]


In [49]:
# Scalar Product
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])
S = np.array ([2])
R = S * A
print(R)

[8 6]


In [52]:
# Dot Product
import numpy as np
A = np.array ([4,3])
B = np.array ([2,-5])
R = A * B
print(R)

[  8 -15]


In [53]:
# Cross Product
import numpy as np
A = np.array ([4,3])
B = np.array ([[2],[-5]])
R = A * B
print(R)

[[  8   6]
 [-20 -15]]


In [65]:
# Property of Matrix
# Identity Matrix
e = np.eye(3,3)
print (e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [66]:
# Property of Matrix
# Identity Matrix
# Zero Matrix
z = np.zeros([5,5])
print (z)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [67]:
# Property of Matrix
# Identity Matrix
# Full Matrix
f = np.full([8,8],8)
print (f)

[[8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8]]


In [64]:
# Property of Matrix
# Identity Matrix
# Transpose Matrix
a = np.array ([[5,3],[6,8]])
t = np.transpose(a)
print (a)

[[5 3]
 [6 8]]
